---
title: "Worksheet1"
author: "Gabriel R. Benedicto"
date: "2024-09-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.
a. How many data points?  34
b.
```{r}
  age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41
)
```
```{r}
length(age)
```
2. Find the reciprocal
```{r}
rec <- 1 / age
```

```{r}
library(MASS)
fractions(rec)
```
3. ASSIGN
The vector repeats the output of the age but the 0 seperates the two age's outputs
```{r}
new_age <- c(age, 0, age)
new_age
```
4. SORT
```{r}
sort(age)
```
5. MAX MIN
```{r}
max(age)
min(age)
```
6. SET VECTOR
b.
```{r}
vec <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)
```
a.
```{r}
length(vec)
```
7.
```{r}
double <- vec * 2
double
```
8.1
```{r}
hundred <- seq(1:100)
```
8.2
```{r}
nums <- seq(20, 60)
```
8.3
```{r}
 mean(nums)
```
8.4
```{r}
sum(51:91)
```
8.5
```{r}
thousands <- seq(1:1000)
```
8.6
a. 143
b.
```{r}
length(hundred) + length(nums) + length(mean) + length(sum)
```
c.
```{r}
max(thousands[thousands <- 10])
```

9.
```{r}
Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
```
10.
```{r}
 ten <- seq(100,1)
ten
```
11.
```{r}
numbers <- 1:24
multiples <- numbers[numbers %% 3 == 0 | numbers %% 5 == 0]
print(multiples)
```
```{r}
sum_multiples <- sum(multiples)
print(sum_multiples)
```
a. 136
b.
```{r}
length(ten) + length(numbers) + length(multiples) + length(sum_multiples)
```
12. It shows an Error unexpedted '}'
```{r}
#x <- {0 + x + 5 + }
```


13.
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75,
75, 77.)
score[2]
score[3]
```
14.
```{r}
 a = c(1,2,NA,4,NA,6,7)
```
a.
```{r}
print(a,na.print="-999")
```
b. the output is [1] 1 2 -999 4 - 999 6 7 
15.
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```
The output of the code above is the name that you input and the age and print it.


























